### ISSUE TITLE
pls help to advise

### ISSUE THREAD

**Issue by hjcxlp** [MaletteAI/anytext#2]
Traceback (most recent call last):
  File "D:\anytext\main.py", line 30, in <module>
    results, rtn_code, rtn_warning = pipe(
  File "D:\anytext\anytext_pipeline.py", line 306, in __call__
    samples, intermediates = self.ddim_sampler.sample(
  File "D:\anytext\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\anytext\cldm\ddim_hacked.py", line 103, in sample
    samples, intermediates = self.ddim_sampling(conditioning, size,
  File "D:\anytext\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\anytext\cldm\ddim_hacked.py", line 163, in ddim_sampling
    outs = self.p_sample_ddim(img, cond, ts, index=index, use_original_steps=ddim_use_original_steps,
  File "D:\anytext\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\anytext\cldm\ddim_hacked.py", line 190, in p_sample_ddim
    model_t = self.model.apply_model(x, t, c)
  File "D:\anytext\cldm\cldm.py", line 445, in apply_model
    control = self.control_model(x=x_noisy, timesteps=t, context=_cond, hint=_hint, text_info=cond['text_info'])
  File "D:\anytext\venv\lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\anytext\venv\lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\anytext\cldm\cldm.py", line 339, in forward
    h = module(h, emb, context)
  File "D:\anytext\venv\lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\anytext\venv\lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\anytext\ldm\modules\diffusionmodules\openaimodel.py", line 84, in forward
    x = layer(x, context)
  File "D:\anytext\venv\lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\anytext\venv\lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\anytext\ldm\modules\attention.py", line 334, in forward
    x = block(x, context=context[i])
  File "D:\anytext\venv\lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\anytext\venv\lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\anytext\ldm\modules\attention.py", line 269, in forward
    return checkpoint(self._forward, (x, context), self.parameters(), self.checkpoint)
  File "D:\anytext\ldm\modules\diffusionmodules\util.py", line 114, in checkpoint
    return CheckpointFunction.apply(func, len(inputs), *args)
  File "D:\anytext\venv\lib\site-packages\torch\autograd\function.py", line 553, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "D:\anytext\ldm\modules\diffusionmodules\util.py", line 129, in forward
    output_tensors = ctx.run_function(*ctx.input_tensors)
  File "D:\anytext\ldm\modules\attention.py", line 272, in _forward
    x = self.attn1(self.norm1(x), context=context if self.disable_self_attn else None) + x
  File "D:\anytext\venv\lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\anytext\venv\lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\anytext\ldm\modules\attention.py", line 192, in forward
    out = einsum('b i j, b j d -> b i d', sim, v)
  File "D:\anytext\venv\lib\site-packages\torch\functional.py", line 380, in einsum
    return _VF.einsum(equation, operands)  # type: ignore[attr-defined]
RuntimeError: expected scalar type Half but found Float

**Comment by jinchanz** [comment]
https://github.com/MaletteAI/anytext/blob/fa9a1fe714808cf612cd95f4cbae125d42a52343/main.py#L13

try setting `use_fp16` to False
